# Generated by Django 4.1.2 on 2023-04-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordrecord',
            name='instance_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
